#include <math.h>
#include <stdio.h>
#include "atom.h"
#include "system.h"

double norm(double *v)
{
  double norm = 0.0;

  for (int i = 0; i < 3; i++)
  {
    norm += v[i] * v[i];
  }

  norm = sqrt(norm);

  return norm;
}

void pbc(Atom *atom, double *box)
{
  for (int i = 0; i < 3; i++)
  {
    while (atom->q[i] > box[i])
    {
      atom->q[i] -= box[i];
    }

    while (atom->q[i] < 0.0)
    {
      atom->q[i] += box[i];
    }
  }

  return;
}

void output_gro(System *system, int step, FILE *file)
{
  fprintf(file, "Generated by md step=%d, t=%f\n", step, step * system->dt);
  fprintf(file, "%d\n", system->natoms);
  for (int i = 0; i < system->natoms; i++)
  {
    fprintf(file, "%5d%-5s%5s%5d%8.3f%8.3f%8.3f%8.4f%8.4f%8.4f\n", i, "Xe", "Xe", i, system->atoms[i].q[0], system->atoms[i].q[1], system->atoms[i].q[2], system->atoms[i].p[0], system->atoms[i].p[1], system->atoms[i].p[2]);
  }
  fprintf(file, "%10.5f%10.5f%10.5f\n", system->box[0], system->box[1], system->box[2]);

  return;
}